export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_ADD_INCREMENT = 'CART_ADD_INCREMENT'
export const CART_ADD_DECREMENT = 'CART_ADD_DECREMENT'


export const CART_TOGGLE = 'CART_TOGGLE'
export const CART_TOGGLE_OPEN = 'CART_TOGGLE_OPEN'
export const CART_TOGGLE_CLOSE = 'CART_TOGGLE_CLOSE'

